# Setup
title:               Matthew ManoX
tagline:             'Welcome to my personal website'
description:         'My little corner of the internet'
url:                 http://matthewm3109.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Matthew Mano
  url:               https://www.linkedin.com/in/matthewm3109/
  email:             matthewm3109@gmail.com 

# Gems
plugins:
  - jekyll-paginate
gems: [jekyll-paginate]
paginate_path: "page:num" 

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
